name: the task runner

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '20 03 * * *'
    - cron:  '20 06 * * *'
    - cron:  '20 11 * * *'
    - cron:  '20 16 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run the overall task
        env:
            PRIVATE_BASE_KEY: ${{ secrets.PRIVATE_BASE_KEY }}
            PRIVATE_API_KEY_AIRTABLE: ${{ secrets.PRIVATE_API_KEY_AIRTABLE }}
            PRIVATE_TABLE_NAME_NEWSPAYLOAD: ${{ secrets.PRIVATE_TABLE_NAME_NEWSPAYLOAD }}
        run: |
          python task.py

      - uses: gautamkrishnar/keepalive-workflow@master
